# Generated by Django 3.1.3 on 2020-11-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201123_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.BigIntegerField(blank=True, max_length=9999999999),
        ),
    ]
