# Generated by Django 3.1.3 on 2020-11-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201123_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.BigIntegerField(blank=True, max_length=9999999999, null=True),
        ),
    ]
