# Generated by Django 3.1.3 on 2020-11-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201130_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.store'),
        ),
    ]
