# Generated by Django 3.1.3 on 2020-12-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_deliverable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store_id',
        ),
    ]
