# Generated by Django 3.1.3 on 2020-12-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201208_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='store_id',
        ),
    ]
