# Generated by Django 3.1.3 on 2020-12-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201209_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
